---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# covidmonitor

<!-- badges: start -->
<!-- badges: end -->

The goal of {covidmonitor} is to provide functions for simplifying data merging 
and cleaning for WHO AFRO COVID-19 linelists and monitoring & evaluation data. 
The package further contains templates for automating report production. 

## Installation

Currently the package is not on CRAN. Once it is - you can install the released 
version of epichecks from [CRAN](https://CRAN.R-project.org) with:

``` r
# install.packages("covidmonitor")
```

In order to install the package you will first need to install an extra bit of 
software called [Rtools](https://cran.r-project.org/bin/windows/Rtools/).  
You can download the installer from: https://cran.r-project.org/bin/windows/Rtools/  
Please install the version highlighted in green. 

Once this is installed and you have restarted your computer, 
the development version of the package can be installed from [GitHub](https://github.com/) with:

``` r
# install.packages("remotes")
remotes::install_github("R4IDSR/covidmonitor")
```

If you do not have a LaTeX editor installed on your computer, then please run the
following code to install TinyTex. This is needed in order to be able to create
Word and PDF documents using *R markdown*. 

```r
install.packages('tinytex')
tinytex::install_tinytex()
# to uninstall TinyTeX, run tinytex::uninstall_tinytex() 
```


## Country linelists

### Folder structure 

TODO: add details about where data should be and how should be named etc 

### Dictionaries 

TODO: add details about how to structure dictionaries (if not using defaults)

### Templates 

TODO: add details about how to use templates

### Other 

TODO: add a note on the TCD 1904 date origin issue




## Monitoring & Evaluation

### Folder structure 

TODO: add details about where data should be and how should be named etc 

### Dictionaries 

TODO: add details about how to structure dictionaries (if not using defaults)

### Templates 

TODO: add details about how to use templates

